### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by skofgar** [gvsucis/mobile-app-dev-book#18]
I think I have identified a few typos for review:

**Git commit:** 49544a9 
**Date:** 2017-08-28

**Page:** xxv:13
- [ ] When talking about Swift the word `on-line` is being used. I think it should be `online`
- [ ] I also noticed you're talking about Java, do you think you should mention Kotlin (e.g. that it is not part of this book or something about it)? **edit:** Just noticed Kotlin is mentioned later on page 4.

**Page:** xxvi:21
- [ ] show instead of shown – `For example, we often **show** a method of a class or a
22 small fragment of code without the entire class context`. Alternatively, if past tense is desired it should probably be `have shown`, but then the sentence might require more changes.

**Page:** 1:11
- [ ] `App Store` instead of `AppStore`. Apple generally has a space between the App and Store [via](https://www.apple.com/ios/app-store/). This `typo` can be observed throughout the entire document.

**Comment by jengelsma** [comment]
Roland - fantastic feedback, thank you very much!  Hans has actually a branch of the book where all of the Android examples are given in Kotlin instead of Java.  In class we are still teaching Java, but we will allow the publisher (still TBD) to make the Kotlin vs Java call based on their understanding of the market.

**Comment by jengelsma** [comment]
Closed. Commit 728a57d
